Create testdataset of the whole dataset, not segmenting into training and validation

In [1]:
from tensorflow.keras.utils import to_categorical
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
import numpy as np

from scipy.io import arff
import pandas as pd

I0000 00:00:1780914576.846439   12783 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2, in other operations, rebuild TensorFlow with the appropriate compiler flags.


Alternative if fetch_openml method doesn't work:

The dataset arff file can be downloaded from \
https://www.openml.org/search?type=data&sort=runs&id=42468&status=active \
and then manually loaded for processing.

In [2]:
!wget https://www.openml.org/data/download/21854360/hls4ml_HLF.arff

--2026-06-08 12:21:08--  https://www.openml.org/data/download/21854360/hls4ml_HLF.arff
Resolving www.openml.org (www.openml.org)... 131.155.10.137
Connecting to www.openml.org (www.openml.org)|131.155.10.137|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 252046372 (240M) [text/plain]
Saving to: ‘hls4ml_HLF.arff’

hls4ml_HLF.arff     100%[===================>] 240.37M  8.45MB/s    in 28s     

2026-06-08 12:21:36 (8.56 MB/s) - ‘hls4ml_HLF.arff’ saved [252046372/252046372]



In [2]:
data_arff, meta = arff.loadarff('hls4ml_HLF.arff')
df = pd.DataFrame(data_arff)

df['class'] = df['class'].str.decode('utf-8')

X = df.drop(columns=['class'])
y = df['class']

print(f"Features: {X.shape[1]}, Samples: {X.shape[0]}")

Features: 16, Samples: 830000


In [3]:
print(X.shape, y.shape)
print(X[:5])
print(y[:5])

(830000, 16) (830000,)
      zlogz  c1_b0_mmdt  c1_b1_mmdt  c1_b2_mmdt  c2_b1_mmdt  c2_b2_mmdt  \
0 -2.935125    0.383155    0.005126    0.000084    0.009070    0.000179   
1 -1.927335    0.270699    0.001585    0.000011    0.003232    0.000029   
2 -3.112147    0.458171    0.097914    0.028588    0.124278    0.038487   
3 -2.666515    0.437068    0.049122    0.007978    0.047477    0.004802   
4 -2.484843    0.428981    0.041786    0.006110    0.023066    0.001123   

   d2_b1_mmdt  d2_b2_mmdt  d2_a1_b1_mmdt  d2_a1_b2_mmdt  m2_b1_mmdt  \
0    1.769445    2.123898       1.769445       0.308185    0.135687   
1    2.038834    2.563099       2.038834       0.211886    0.063729   
2    1.269254    1.346238       1.269254       0.246488    0.115636   
3    0.966505    0.601864       0.966505       0.160756    0.082196   
4    0.552002    0.183821       0.552002       0.084338    0.048006   

   m2_b2_mmdt  n2_b1_mmdt  n2_b2_mmdt   mass_mmdt  multiplicity  
0    0.083278    0.412136    0.29

One-hot encoding (Optional) 

In [4]:
le = LabelEncoder()
y = le.fit_transform(y)
y = to_categorical(y, 5)
X_test = X
y_test = y

In [5]:
scaler = StandardScaler()
X_test = scaler.fit_transform(X_test)

In [6]:
print(X_test, y_test)

[[-0.12023353 -0.90476494 -1.11957654 ...  1.92817227 -1.19085998
   1.06620575]
 [ 1.61617265 -2.93292487 -1.24101711 ...  1.028402   -1.28149371
  -0.9635933 ]
 [-0.4252383   0.44814915  2.06311284 ...  1.80589858  1.56423505
   0.4203606 ]
 ...
 [-0.81586924  0.60758053  1.28521466 ...  0.49179737  1.09709721
   0.92781036]
 [ 2.29049424 -1.76583004 -1.20838603 ...  0.22251231 -1.26756993
  -1.88622923]
 [-0.21132692  0.40263856 -1.1164129  ...  1.41745318 -1.14360095
  -0.45614353]] [[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [7]:
np.save('X_test.npy', X_test)
np.save('y_test.npy', y_test)
np.save('classes.npy', le.classes_)